### ISSUE TITLE
添加更多应用的伪装

### ISSUE THREAD

**Issue by wushidia** [nelwang/MiPushFakeForZygisk#1]
包名：
com.tencent.androidqqmail
info.muge.appshare
com.chinamworld.main
com.eg.android.AlipayGphone
com.android.calendar
com.miui.weather2
com.jingdong.app.mall
com.android.email
com.chaoxing.mobile
com.tencent.wemeet.app

**Comment by nelwang** [comment]
Added with latest commit.
