### ISSUE TITLE
麻烦添加以下应用的伪装

### ISSUE THREAD

**Issue by ballyhuang** [nelwang/MiPushFakeForZygisk#3]
包名：
com.nowcasting.activity
com.hpbr.bosszhipin
com.zhaopin.social
com.taobao.etao
com.cib.cibmb
com.sina.weibo
com.job.android
net.evecom.android.mztapp
com.xiaomi.smarthome
today.tophub.app
com.cebbank.mobile.cemb
com.duoduo.tuanzhang
tv.danmaku.bili
top.tdtt.news
com.xunmeng.pinduoduo 
com.digitalchina.mobile.dfhfz1
com.ss.android.article.news

**Comment by nelwang** [comment]
Added in latest commit.
