### ISSUE TITLE
请求添加以下包名

### ISSUE THREAD

**Issue by UQJRlex** [nelwang/MiPushFakeForZygisk#4]
com.baidu.netdisk.samsung
com.baidu.tieba
com.chinamobile.mcloud
com.dragon.read
com.dmzj.manhua
com.dmzjsq.manhua
com.douban.frodo
com.faloo.BookReader4Android
com.greenpoint.android.mc10086.activity
com.kuangxiangciweimao.novel
com.nowcasting.activity
com.novel.du
com.qidian.QDReader
com.readunion.ireader
com.sfacg
com.sitech.ac
com.tencent.mp
com.xunlei.downloadprovider
com.xingin.xhs
com.xunyou.rb
com.yingyonghui.market
com.youdu
com.youdao.translator
cn.wps.moffice_eng
hanjie.app.pureweather
nutstore.android

**Comment by nelwang** [comment]
Added in latest commit.
